---
title: "em extension work"
output: html_notebook
editor_options: 
  chunk_output_type: console
---


```{r}

pubsafhr2106<-read_sas(here("srtr_sas_files","tx_hr.sas7bdat"))
pubsafli2106<-read_sas(here("srtr_sas_files","tx_li.sas7bdat"))
pubsaflu2106<-read_sas(here("srtr_sas_files"))
pubsafki2106<-read_sas(here("srtr_sas_files","tx_ki.sas7bdat"))

pubsaf2106<-bind_rows(pubsafhr2106,pubsafli2106,pubsaflu2106,pubsafki2106)
save(pubsaf2106,file="pubsaf2106.rdata")

pubsafinst2106<-read_sas(here("srtr_sas_files","institution.sas7bdat"))%>%
  dplyr::select(CTR_CD,REGION)%>%mutate(REGION=factor(REGION),CTR_CD=factor(CTR_CD))
load(file="pubsaf2106.rdata")

pubsaf2106v2<-pubsaf2106%>%
  filter(ORG_TY%in%c("KI","LU","LI","HR"))%>%
  mutate(across(c(PERS_ID,ORG_TY,CAN_GENDER,CAN_RACE_SRTR,
                  CAN_ETHNICITY_SRTR,REC_GRAFT_STAT,REC_CTR_CD),
                factor))%>%
  group_by(PERS_ID)%>%
  mutate(DEATH_DATE=pmin(PERS_SSA_DEATH_DT,
                         PERS_OPTN_DEATH_DT,
                         PERS_RESTRICT_DEATH_DT,
                         TFL_DEATH_DT,na.rm=T))%>%
  arrange(PERS_ID,REC_TX_DT)%>%
  filter(REC_TX_DT==min(REC_TX_DT))%>%
  ungroup()%>%
  mutate(DEATH_EVENT=ifelse(!is.na(DEATH_DATE),"DEAD","ALIVE"))%>%
  mutate(ds=(ceiling_date(DEATH_DATE,unit="month")-days(1)),
         AGE_DEATH=floor(REC_AGE_AT_TX+(time_length(difftime(DEATH_DATE,REC_TX_DT),"years"))),
         AGE_GROUP=as.factor(case_when(
    REC_AGE_AT_TX<25~"<25",
    REC_AGE_AT_TX>=25&REC_AGE_AT_TX<=44~"25-44",
    REC_AGE_AT_TX>=45&REC_AGE_AT_TX<=64~"45-64",
    REC_AGE_AT_TX>=65~"65+")),
    AGE_GROUP=fct_relevel(AGE_GROUP,"<25","25-44","45-64","65+"))%>%
  filter(is.na(ds)|(ds>="2014-01-01"&ds<="2021-06-01"))%>%
  mutate(COVID_DEATH=case_when(
           ORG_TY=="HR"&TFL_COD==2804~1,
           ORG_TY=="LU"&TFL_COD==2804~1,
           ORG_TY=="LI"&TFL_COD==4959~1,
           ORG_TY=="KI"&TFL_COD==3916~1,
           TRUE~0),
         
        CAN_ETHINICITY_SRTR=factor(case_when(
          CAN_ETHNICITY_SRTR=="LATINO"~"Hispanic",
          CAN_ETHNICITY_SRTR=="NLATIN"~"Non-Hispanic")),
        
        CAN_RACE_SRTR=factor(case_when(
          CAN_RACE_SRTR=="ASIAN"~"Asian",
          CAN_RACE_SRTR=="BLACK"~"Black",
          CAN_RACE_SRTR=="MULTI"~"Other",
          CAN_RACE_SRTR=="NATIVE"~"Other",
          CAN_RACE_SRTR=="PACIFIC"~"Other",
          CAN_RACE_SRTR=="WHITE"~"White")))%>%
  dplyr::select(ORG_TY,PERS_ID,REC_TX_DT,DEATH_EVENT,DEATH_DATE,CAN_GENDER,
         ds,REC_AGE_AT_TX,AGE_GROUP,REC_CTR_CD,
         REC_GRAFT_STAT,COVID_DEATH,CAN_ETHNICITY_SRTR,CAN_RACE_SRTR,
         REC_COD,REC_COD2,REC_COD3,TFL_COD,AGE_DEATH)%>%
  left_join(.,pubsafinst2106,by=c("REC_CTR_CD"="CTR_CD"))%>%
  mutate(GROUP1=factor(paste("ORGAN","",ORG_TY)),
         GROUP2=factor(paste("AGE","",AGE_GROUP)),
         GROUP3=factor(paste("RACE","",CAN_RACE_SRTR)),
         GROUP4=factor(paste("ETHNICITY","",CAN_ETHNICITY_SRTR)),
         GROUP5=factor(paste("KI GRAFT","",REC_GRAFT_STAT)),
         GROUP6=factor(paste(ORG_TY,AGE_GROUP)),
         GROUP7=factor(paste(ORG_TY,CAN_RACE_SRTR)),
         GROUP8=factor(paste(ORG_TY,CAN_ETHNICITY_SRTR)),
         GROUP9=factor(paste(ORG_TY,REGION)),
         GROUP10=factor(paste(REGION)),
         GROUP11=factor("SRTR ALL"),
         GROUP12=ifelse(REC_CTR_CD=="MOBH","MOBH","OTHER"),
         GROUP12=factor(GROUP12),
         GROUP13=factor(paste(GROUP12,GROUP1)))%>%
  pivot_longer(cols=starts_with("GROUP"),names_to="GROUP",values_to="SUBGROUP")

save(pubsaf2106v2,file="pubsaf2106v2.rdata")

rm(pubsafhr2106,pubsafki2106,pubsaflu2106,pubsafli2106,pubsafinst2106)


date.list<-ceiling_date(seq(ymd("2014-02-01"),ymd("2021-05-01"),"month")-days(1))%>%as.Date
date.list2<-floor_date(seq(ymd("2014-01-01"),ymd("2021-04-01"),"month"))%>%as.Date


mortality_counts<-pubsaf2106v2%>%
  group_by(ds,GROUP,SUBGROUP)%>%
  mutate(y=length(PERS_ID),y_c19=sum(COVID_DEATH))%>%
  ungroup()%>%
  complete(ds)%>%
  distinct(ds,y,y_c19,GROUP,SUBGROUP)%>%
  mutate(elapsed_months=interval("2020-02-28",ds)%/%months(1))%>%
  filter(!is.na(ds))%>%
  dplyr::select(GROUP,SUBGROUP,ds,elapsed_months,y,y_c19,)%>%
  arrange(GROUP,SUBGROUP,ds,elapsed_months)%>%
  distinct(.keep_all=T)%>%mutate(GROUP=factor(GROUP))

tmp<-data.frame()
predictSAF<-function(){
for(k in unique(mortality_counts$SUBGROUP)){
tmp2<-mortality_counts%>%filter(elapsed_months<=0,SUBGROUP==k)
srtr_model<-prophet(tmp2)
tmp3<-mortality_counts%>%filter(SUBGROUP==k)
srtr_forecast<-predict(srtr_model,tmp3)%>%tibble()%>%bind_cols(.,tmp3)
tmp<<-bind_rows(tmp,srtr_forecast)}}
predictSAF()
tmp<<-tmp%>%mutate(ds=ymd(ds...1))%>%
  dplyr::select(GROUP,SUBGROUP,ds,elapsed_months,y,y_c19,yhat_lower,yhat,yhat_upper)

tmp2<-data.frame()
  prevalence_fxn<-function(){
    for (j in 1:length(date.list2)){
      tmp3<-pubsaf2106v2%>%group_by(SUBGROUP)%>%
        filter(REC_TX_DT<date.list2[j],(DEATH_DATE>date.list2[j]|is.na(DEATH_DATE)))%>%
        count(name="population")%>%ungroup()%>%bind_cols(.,date.list2[j])
      tmp2<<-rbind(tmp2,tmp3)
    }
  }
  prevalence_fxn()
  
  prevalence<-tmp2%>%rename(ds=...3)%>%
    mutate(ds=ceiling_date(ds,"month")-days(1),
           elapsed_months=interval("2020-02-01",ds)%/%months(1))%>%
    dplyr::select(SUBGROUP,ds,elapsed_months,population)%>%distinct()
  
EM_SAF<-left_join(tmp,prevalence,by=c("SUBGROUP","ds","elapsed_months"))
save(EM_SAF,file="EM_SAF.rdata")



dir()

EM_SAFwCALC<-EM_SAF%>%
  group_by(SUBGROUP)%>%
  mutate(
    percapita=10000,
    `Cumulative observed deaths`=cumsum(ifelse(elapsed_months>0,y,0)),
    `Cumulative observed deaths from COVID-19`=cumsum(ifelse(elapsed_months>0,y_c19,0)),
    `Cumulative expected deaths`=cumsum(ifelse(elapsed_months>0,yhat,0)),
    `Cumulative expected deaths lwr`=cumsum(ifelse(elapsed_months>0,yhat_lower,0)),
    `Cumulative expected deaths upr`=cumsum(ifelse(elapsed_months>0,yhat_upper,0)),
    `Cumulative excess deaths`=cumsum(ifelse(elapsed_months>0,y-yhat,0)),
    `Cumulative excess deaths lwr`=cumsum(ifelse(elapsed_months>0,y-yhat_upper,0)),
    `Cumulative excess deaths upr`=cumsum(ifelse(elapsed_months>0,y-yhat_lower,0)),
    `Cumulative excess deaths 10k`=cumsum(ifelse(elapsed_months>0,percapita*((y-yhat)/population),0)),
    `Cumulative excess deaths 10k lwr`=
      cumsum(ifelse(elapsed_months>0,percapita*((y-yhat_upper)/population),0)),
    `Cumulative excess deaths 10k upr`=
      cumsum(ifelse(elapsed_months>0,percapita*((y-yhat_lower)/population),0)),
    `Excess mortality from COVID-19(%)`=
      paste0(round(100*(cumsum(y_c19)/
                          `Cumulative excess deaths`),1),"%"))%>%
    ungroup()
      
save(EM_SAFwCALC,file="EM_SAFwCALC.rdata")


(EM_SAFwCALC%>%filter(GROUP=="GROUP10",elapsed_months>0,elapsed_months<15)%>%
    mutate(SUBGROUP=fct_relevel(SUBGROUP,"1","2","3","4","5","6","7","8","9","10"))%>%
    ggplot(aes(x=elapsed_months))+
    geom_line(aes(y=`Cumulative excess deaths 10k`),size=.5)+
    geom_point(aes(y=`Cumulative excess deaths 10k`),size=2.2)+
    theme_minimal()+
   facet_wrap(.~SUBGROUP)+
   scale_x_continuous(breaks=seq(0,15,3)))

mygraph_fxn<-function(x){
  (EM_SAFwCALC%>%filter(GROUP==x,elapsed_months>0,elapsed_months<15)%>%
  ggplot(aes(x=elapsed_months))+
  geom_line(aes(y=`Cumulative excess deaths 10k`,color=SUBGROUP),size=.75)+
  geom_point(aes(y=`Cumulative excess deaths 10k`,color=SUBGROUP),size=3)+
  theme_minimal()+scale_color_jama()+scale_fill_jama()+
  scale_x_continuous(breaks=seq(0,15,2),limits=c(1,14)))
}

mygraph_fxn("GROUP1")
mygraph_fxn("GROUP2")
mygraph_fxn("GROUP3")
mygraph_fxn("GROUP4")
mygraph_fxn("GROUP5")
mygraph_fxn("GROUP6")
mygraph_fxn("GROUP7")
mygraph_fxn("GROUP8")
mygraph_fxn("GROUP9")
mygraph_fxn("GROUP10")
mygraph_fxn("GROUP11")
mygraph_fxn("GROUP12")

(EM_SAFwCALC%>%filter(GROUP=="GROUP13")%>%dplyr::select(SUBGROUP)%>%distinct())

(EM_SAF%>%
    filter(GROUP=="GROUP13"&
           SUBGROUP%in%(c(
            "MOBH ORGAN  HR",
           "MOBH ORGAN  KI",
           "MOBH ORGAN  LI",
           "MOBH ORGAN  LU")),
           elapsed_months>0,
           elapsed_months<15)%>%
    ggplot(aes(x=elapsed_months))+
    geom_col(aes(y=y),fill="lightgray")+
    geom_point(aes(y=y_c19))+
    facet_wrap(.~SUBGROUP)+
    theme_minimal())

# cause of death
(deaths<-pubsaf2106v2%>%
    filter(REC_CTR_CD=="MOBH",DEATH_DATE>"2019-12-31",DEATH_DATE<"2021-06-02")%>%
    mutate(across(c(REC_COD,REC_COD2,REC_COD3,TFL_COD),factor))%>%
    dplyr::select(ORG_TY,DEATH_DATE,REC_COD,REC_COD2,REC_COD3,TFL_COD)%>%
    arrange(DEATH_DATE)%>%distinct())

write.csv(deaths,file="deaths.csv")

# how many are all NA

(deathsna<-pubsaf2106v2%>%
    filter(REC_CTR_CD=="MOBH",DEATH_DATE>"2019-12-31",DEATH_DATE<"2021-06-02")%>%
    mutate(across(c(REC_COD,REC_COD2,REC_COD3,TFL_COD),factor))%>%
    mutate(ALLNA=ifelse((is.na(REC_COD)|REC_COD==999)&
                        (is.na(REC_COD2)|REC_COD==999)&
                        (is.na(REC_COD3)|REC_COD3==999)&
                        (is.na(TFL_COD)|TFL_COD==999),1,0))%>%
    dplyr::select(ORG_TY,DEATH_DATE,REC_COD,REC_COD2,REC_COD3,TFL_COD,ALLNA)%>%
    arrange(DEATH_DATE)%>%distinct())

```  

NEW RELEASE
```{r 2112 NEW RELEASE}

pubsafhr2112<-read_sas(here("dec2021_saf_release","tx_hr.sas7bdat"))
pubsafli2112<-read_sas(here("dec2021_saf_release","tx_li.sas7bdat"))
pubsaflu2112<-read_sas(here("dec2021_saf_release","tx_lu.sas7bdat"))
pubsafki2112<-read_sas(here("dec2021_saf_release","tx_ki.sas7bdat"))

pubsaf2112<-bind_rows(pubsafhr2112,pubsafli2112,pubsaflu2112,pubsafki2112)
save(pubsaf2112,file="pubsaf2112.rdata")
pubsafinst2112<-read_sas(here("dec2021_saf_release","institution.sas7bdat"))%>%
  dplyr::select(CTR_CD,REGION,PRIMARY_STATE)%>%mutate(REGION=factor(REGION),CTR_CD=factor(CTR_CD),
                                        PRIMARY_STATE=factor(PRIMARY_STATE))
load("pubsaf2112.rdata")

pubsaf2112v2<-function(){
  pubsaf2112v2<<-pubsaf2112%>%
  filter(ORG_TY%in%c("KI","LU","LI","HR"))%>%
  mutate(across(c(PERS_ID,ORG_TY,CAN_GENDER,CAN_RACE_SRTR,
                  CAN_ETHNICITY_SRTR,REC_GRAFT_STAT,REC_CTR_CD),
                factor))%>%
  group_by(PERS_ID)%>%
  mutate(DEATH_DATE=pmin(PERS_SSA_DEATH_DT,
                         PERS_OPTN_DEATH_DT,
                         TFL_DEATH_DT,na.rm=T))%>%
  arrange(PERS_ID,REC_TX_DT)%>%
  filter(REC_TX_DT==min(REC_TX_DT))%>%
  ungroup()%>%
  mutate(DEATH_EVENT=ifelse(!is.na(DEATH_DATE),"DEAD","ALIVE"))%>%
  mutate(ds=(ceiling_date(DEATH_DATE,unit="month")-days(1)),
         AGE_DEATH=floor(REC_AGE_AT_TX+(time_length(difftime(DEATH_DATE,REC_TX_DT),"years"))),
         AGE_GROUP=as.factor(case_when(
    REC_AGE_AT_TX<25~"<25",
    REC_AGE_AT_TX>=25&REC_AGE_AT_TX<=44~"25-44",
    REC_AGE_AT_TX>=45&REC_AGE_AT_TX<=64~"45-64",
    REC_AGE_AT_TX>=65~"65+")),
    AGE_GROUP=fct_relevel(AGE_GROUP,"<25","25-44","45-64","65+"))%>%
  filter(is.na(ds)|(ds>="2014-01-01"&ds<="2021-12-31"))%>%
  mutate(COVID_DEATH=case_when(
           ORG_TY=="HR"&TFL_COD==2804~1,
           ORG_TY=="LU"&TFL_COD==2804~1,
           ORG_TY=="LI"&TFL_COD==4959~1,
           ORG_TY=="KI"&TFL_COD==3916~1,
           TRUE~0),
         
        CAN_ETHINICITY_SRTR=factor(case_when(
          CAN_ETHNICITY_SRTR=="LATINO"~"Hispanic",
          CAN_ETHNICITY_SRTR=="NLATIN"~"Non-Hispanic")),
        
        CAN_RACE_SRTR=factor(case_when(
          CAN_RACE_SRTR=="ASIAN"~"Asian",
          CAN_RACE_SRTR=="BLACK"~"Black",
          CAN_RACE_SRTR=="MULTI"~"Other",
          CAN_RACE_SRTR=="NATIVE"~"Other",
          CAN_RACE_SRTR=="PACIFIC"~"Other",
          CAN_RACE_SRTR=="WHITE"~"White")))%>%
  dplyr::select(ORG_TY,PERS_ID,REC_TX_DT,DEATH_EVENT,DEATH_DATE,CAN_GENDER,
         ds,REC_AGE_AT_TX,AGE_GROUP,REC_CTR_CD,
         REC_GRAFT_STAT,COVID_DEATH,CAN_ETHNICITY_SRTR,CAN_RACE_SRTR,
         REC_COD,REC_COD2,REC_COD3,TFL_COD,AGE_DEATH)%>%
  left_join(.,pubsafinst2112,by=c("REC_CTR_CD"="CTR_CD"))%>%
  mutate(GROUP1=factor(paste("ORGAN","",ORG_TY)),
         GROUP2=factor(paste("AGE","",AGE_GROUP)),
         GROUP3=factor(paste("RACE","",CAN_RACE_SRTR)),
         GROUP4=factor(paste("ETHNICITY","",CAN_ETHNICITY_SRTR)),
         GROUP5=factor(paste("KI GRAFT","",REC_GRAFT_STAT)),
         GROUP6=factor(paste(ORG_TY,AGE_GROUP)),
         GROUP7=factor(paste(ORG_TY,CAN_RACE_SRTR)),
         GROUP8=factor(paste(ORG_TY,CAN_ETHNICITY_SRTR)),
         GROUP9=factor(paste(ORG_TY,REGION)),
         GROUP10=factor(paste(REGION)),
         GROUP11=factor("SRTR ALL"),
         GROUP12=ifelse(REC_CTR_CD=="MOBH","MOBH","OTHER"),
         GROUP12=factor(GROUP12),
         GROUP13=factor(paste(GROUP12,GROUP1)),
         GROUP14=factor(PRIMARY_STATE))%>%
  pivot_longer(cols=starts_with("GROUP"),names_to="GROUP",values_to="SUBGROUP")
  
  save(pubsaf2112v2,file="pubsaf2112v2.rdata")
  
}

pubsaf2112v2()

save(pubsafhr2112,file="pubsafhr2112.rdata")
save(pubsafli2112,file="pubsafli2112.rdata")
save(pubsafki2112,file="pubsafki2112.rdata")
save(pubsaflu2112,file="pubsaflu2112.rdata")
rm(pubsafhr2112,pubsafki2112,pubsaflu2112,pubsafli2112,pubsafinst2112)

excess_mortality<-function(){

date.list<<-ceiling_date(seq(ymd("2014-02-01"),ymd("2021-12-31"),"month")-days(1))%>%as.Date
date.list2<<-floor_date(seq(ymd("2014-01-01"),ymd("2021-12-31"),"month"))%>%as.Date
  
  mortality_counts<<-pubsaf2112v2%>%
  group_by(ds,GROUP,SUBGROUP)%>%
  mutate(y=length(PERS_ID),
         y_c19=sum(COVID_DEATH))%>%
  ungroup()%>%
  complete(ds)%>%
  distinct(ds,y,y_c19,GROUP,SUBGROUP)%>%
  mutate(elapsed_months=interval("2020-02-28",ds)%/%months(1))%>%
  filter(!is.na(ds))%>%
  dplyr::select(GROUP,SUBGROUP,ds,elapsed_months,y,y_c19,)%>%
  arrange(GROUP,SUBGROUP,ds,elapsed_months)%>%
  distinct(.keep_all=T)%>%
    mutate(GROUP=factor(GROUP))

tmp<<-data.frame()

predictSAF<-function(){
for(k in unique(mortality_counts$SUBGROUP)){
tmp2<-mortality_counts%>%filter(elapsed_months<=0,SUBGROUP==k)
srtr_model<-prophet(tmp2)
tmp3<-mortality_counts%>%filter(SUBGROUP==k)
srtr_forecast<-predict(srtr_model,tmp3)%>%tibble()%>%bind_cols(.,tmp3)
tmp<<-bind_rows(tmp,srtr_forecast)}}
predictSAF()
tmp<<-tmp%>%mutate(ds=ymd(ds...1))%>%
  dplyr::select(GROUP,SUBGROUP,ds,elapsed_months,y,y_c19,yhat_lower,yhat,yhat_upper)

tmp2<<-data.frame()
  prevalence_fxn<-function(){
    for (j in 1:length(date.list2)){
      tmp3<-pubsaf2112v2%>%group_by(SUBGROUP)%>%
        filter(REC_TX_DT<date.list2[j],(DEATH_DATE>date.list2[j]|is.na(DEATH_DATE)))%>%
        count(name="population")%>%ungroup()%>%bind_cols(.,date.list2[j])
      tmp2<<-rbind(tmp2,tmp3)
    }
  }
  prevalence_fxn()
  
  prevalence<<-tmp2%>%rename(ds=...3)%>%
    mutate(ds=ceiling_date(ds,"month")-days(1),
           elapsed_months=interval("2020-02-01",ds)%/%months(1))%>%
    dplyr::select(SUBGROUP,ds,elapsed_months,population)%>%distinct()
  
EM_SAF_2112<<-left_join(tmp,prevalence,by=c("SUBGROUP","ds","elapsed_months"))
save(EM_SAF_2112,file="EM_SAF_2112.rdata")

load(file="EM_SAF_2112.rdata")

EM_SAFwCALC_2112<<-EM_SAF_2112%>%
  group_by(SUBGROUP)%>%
  mutate(
    percapita=10000,
    `Observed Deaths`=y,
    `Expected Deaths`=yhat,
    `O:E`=y/yhat,
    `Cumulative observed deaths`=cumsum(ifelse(elapsed_months>0,y,0)),
    `Cumulative observed deaths from COVID-19`=cumsum(ifelse(elapsed_months>0,y_c19,0)),
    `Cumulative expected deaths`=cumsum(ifelse(elapsed_months>0,yhat,0)),
    `Cumulative expected deaths lwr`=cumsum(ifelse(elapsed_months>0,yhat_lower,0)),
    `Cumulative expected deaths upr`=cumsum(ifelse(elapsed_months>0,yhat_upper,0)),
    `Excess Deaths`=y-yhat,
    `Cumulative excess deaths`=cumsum(ifelse(elapsed_months>0,y-yhat,0)),
    `Cumulative excess deaths lwr`=cumsum(ifelse(elapsed_months>0,y-yhat_upper,0)),
    `Cumulative excess deaths upr`=cumsum(ifelse(elapsed_months>0,y-yhat_lower,0)),
    `Cumulative excess deaths 10k`=cumsum(ifelse(elapsed_months>0,percapita*((y-yhat)/population),0)),
    `Cumulative excess deaths 10k lwr`=cumsum(ifelse(elapsed_months>0,percapita*((y-yhat_upper)/population),0)),
    `Cumulative excess deaths 10k upr`=cumsum(ifelse(elapsed_months>0,percapita*((y-yhat_lower)/population),0)),
    `Excess mortality from COVID-19(%)`=paste0(round(100*(cumsum(y_c19)/`Cumulative excess deaths`),1),"%"))%>%
    ungroup()%>%mutate(SOURCE=factor("SRTR"))

save(EM_SAFwCALC_2112,file="EM_SAFwCALC_2112.rdata")

}
excess_mortality()



(EM_SAFwCALC_2112%>%filter(GROUP=="GROUP10",elapsed_months>0)%>%
    mutate(SUBGROUP=fct_relevel(SUBGROUP,"1","2","3","4","5","6","7","8","9","10"))%>%
    ggplot(aes(x=elapsed_months))+
    geom_line(aes(y=`Cumulative excess deaths 10k`),size=.5)+
    geom_point(aes(y=`Cumulative excess deaths 10k`),size=2.2)+
    theme_minimal()+
   facet_wrap(.~SUBGROUP))

mygraph_fxn<-function(x){
  (EM_SAFwCALC_2112%>%filter(GROUP==x,between(elapsed_months,0,22),SUBGROUP!="RACE  NA",SUBGROUP!="RACE  Other")%>%
  ggplot(aes(x=elapsed_months))+
  geom_line(aes(y=`Cumulative excess deaths 10k`,color=SUBGROUP),size=.75)+
  geom_point(aes(y=`Cumulative excess deaths 10k`,color=SUBGROUP),size=3)+
  theme_minimal()+scale_color_jama()+scale_fill_jama()+theme(legend.position = "top"))
}

mygraph_fxn("GROUP1")
mygraph_fxn("GROUP2")
mygraph_fxn("GROUP3")
mygraph_fxn("GROUP4")
mygraph_fxn("GROUP5")
mygraph_fxn("GROUP6")
mygraph_fxn("GROUP7")
mygraph_fxn("GROUP8")
mygraph_fxn("GROUP9")
mygraph_fxn("GROUP10")
mygraph_fxn("GROUP11")
mygraph_fxn("GROUP13")

(EM_SAFwCALC_2112%>%filter(GROUP=="GROUP13")%>%dplyr::select(SUBGROUP)%>%distinct())

(EM_SAF_2112%>%
    filter(GROUP=="GROUP13"&
           SUBGROUP%in%(c(
            "MOBH ORGAN  HR",
           "MOBH ORGAN  KI",
           "MOBH ORGAN  LI",
           "MOBH ORGAN  LU")),
           elapsed_months>0)%>%
    ggplot(aes(x=elapsed_months))+
    geom_col(aes(y=y),fill="lightgray")+
    geom_point(aes(y=y_c19))+
    facet_wrap(.~SUBGROUP)+
    theme_minimal())

(EM_SAFwCALC_2112%>%
    filter(elapsed_months>0,SUBGROUP%in%c("MS","HI","AZ"))%>%
    dplyr::select(SUBGROUP,ds,`O:E`))

(EM_SAFwCALC_2112%>%
    filter(elapsed_months>0,SUBGROUP%in%c("MS","HI","AZ"))%>%
    mutate(OE=`Cumulative observed deaths`/`Cumulative expected deaths`)%>%
    ggplot(aes(x=ds))+
    geom_line(aes(y=OE,color=SUBGROUP))+theme_minimal())

```
